import type { TierDefinition } from "../types/tiers.js";

export const TIER_DEFINITIONS: TierDefinition[] = [
  {
    id: "111",
    name: "Tier 111",
    description: "Core access — prediction signals and community feed.",
    features: {
      "genie.signals": true,
      "genie.history": false,
      "coach.sessions": false,
      "coach.history": false,
      "dealflow.browse": true,
      "dealflow.post": false,
      "dealflow.interest": false,
      "marketing.email": false,
      "marketing.phone": false,
      "admin.access": false,
    },
    grants: {
      signalsPerDay: 10,
      coachMessagesPerMonth: 0,
      dealPostsPerMonth: 0,
      emailsPerMonth: 0,
      callsPerMonth: 0,
    },
    priceMonthly: 0,
    priceYearly: 0,
  },
  {
    id: "222",
    name: "Tier 222",
    description: "Signals + AI Business Coach access.",
    features: {
      "genie.signals": true,
      "genie.history": true,
      "coach.sessions": true,
      "coach.history": true,
      "dealflow.browse": true,
      "dealflow.post": false,
      "dealflow.interest": true,
      "marketing.email": false,
      "marketing.phone": false,
      "admin.access": false,
    },
    grants: {
      signalsPerDay: 50,
      coachMessagesPerMonth: 100,
      dealPostsPerMonth: 0,
      emailsPerMonth: 0,
      callsPerMonth: 0,
    },
    priceMonthly: 29,
    priceYearly: 290,
  },
  {
    id: "333",
    name: "Tier 333",
    description: "Everything + deal flow and marketing suite.",
    features: {
      "genie.signals": true,
      "genie.history": true,
      "coach.sessions": true,
      "coach.history": true,
      "dealflow.browse": true,
      "dealflow.post": true,
      "dealflow.interest": true,
      "marketing.email": true,
      "marketing.phone": false,
      "admin.access": false,
    },
    grants: {
      signalsPerDay: 200,
      coachMessagesPerMonth: 500,
      dealPostsPerMonth: 10,
      emailsPerMonth: 5000,
      callsPerMonth: 0,
    },
    priceMonthly: 99,
    priceYearly: 990,
  },
  {
    id: "888",
    name: "Tier 888",
    description: "Full platform + private deal rooms + phone outreach.",
    features: {
      "genie.signals": true,
      "genie.history": true,
      "coach.sessions": true,
      "coach.history": true,
      "dealflow.browse": true,
      "dealflow.post": true,
      "dealflow.interest": true,
      "marketing.email": true,
      "marketing.phone": true,
      "admin.access": false,
    },
    grants: {
      signalsPerDay: -1,
      coachMessagesPerMonth: -1,
      dealPostsPerMonth: -1,
      emailsPerMonth: 100000,
      callsPerMonth: 5000,
    },
    priceMonthly: 499,
    priceYearly: 4990,
  },
];
